development:
  clients:
    default:
      database: rhapsody_dev
      hosts:
        - localhost:27017

test:
  clients:
    default:
      database: rhapsody_test
      hosts:
        - localhost:27017

production:
  clients:
    default:
      database: rhapsody_prod
      hosts:
        - localhost:27017
